title: "Apollo Nicolson"
email: apollonicolson@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find some of the things I think about enough to write.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  apruni

# Build settings
theme: just-the-docs
color_scheme: "dark"
search_enabled: true